extends Node

const GAME_IN_PROGRESS = "GAME_IN_PROGRESS"
const GAME_OVER = "GAME_OVER"
const GAME_STARTING = "GAME_STARTING"
const GAME_ESCAPING = "GAME_ESCAPING"
const GAME_TRANSITIONING = "GAME_TRANSITIONING"
const GAME_UPGRADING = "GAME_UPGRADING"
